name: hotel_savior
description: Hotel searching app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #ui helpers
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6

  #di
  injectable: ^2.1.0
  get_it: ^7.2.0

  #router
  go_router: ^6.0.0

  #state_management
  flutter_bloc: ^8.1.0

  #data classes
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0

  #utils
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  #lints
  flutter_lints: ^2.0.0

  #code generation
  build_runner: ^2.3.3
  injectable_generator: ^2.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/