name: hotel_savior
description: Hotel searching app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #ui helpers
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  google_fonts: ^4.0.3
  animations: ^2.0.7
  video_player: ^2.5.3
  flutter_animate: ^4.1.1+1
  flex_color_scheme: ^7.0.4
  mask_text_input_formatter: ^2.4.0
  numberpicker: ^2.1.2
  flutter_pw_validator: ^1.5.0
  awesome_card: ^1.1.7
  cached_network_image: ^3.2.3
  dots_indicator: ^3.0.0

  #maps
  google_maps_flutter: ^2.2.8
  geocoding: ^2.1.0

  #html parser
  html: ^0.15.3

  #qr code generator
  qr_flutter: ^4.1.0

  #di
  injectable: ^2.1.0
  get_it: ^7.2.0

  #router
  go_router: ^6.0.0

  #state_management
  flutter_bloc: ^8.1.0
  provider: ^6.0.5
  flutter_hooks: ^0.18.6

  #localization
  easy_localization: ^3.0.1

  #data classes
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0

  #utils
  logger: ^1.1.0

  #dart extensions
  rxdart: ^0.27.7

  #helpers
  form_validator: ^2.1.1

  #firebase
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  firebase_database: ^10.0.14
  firebase_storage: ^11.0.14
  cloud_firestore: ^4.4.3
  firebase_messaging: ^14.5.0

  #local storages
  flutter_secure_storage: ^8.0.0

  # biometric auth
  local_auth: ^2.1.6

  #serializers
  json_annotation: ^4.8.1

  #push notifications
  flutter_local_notifications: ^14.0.0+1

  #dart extensions
  collection: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  #lints
  dart_code_metrics: ^5.6.0

  #code generation
  build_runner: ^2.3.3
  injectable_generator: ^2.1.3

  #serializers
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/videos/