// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4rKPPME0cQd0h71yBdAs_I3xCsPmB1C8',
    appId: '1:638499786075:android:a07b407f9dfddfe9fb9e7e',
    messagingSenderId: '638499786075',
    projectId: 'hotel-savior-b57f7',
    databaseURL: 'https://hotel-savior-b57f7-default-rtdb.firebaseio.com',
    storageBucket: 'hotel-savior-b57f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPQw9xGfL5icgsGdGdCMtC3LQaOCbrh10',
    appId: '1:638499786075:ios:199dc9469dd16df3fb9e7e',
    messagingSenderId: '638499786075',
    projectId: 'hotel-savior-b57f7',
    databaseURL: 'https://hotel-savior-b57f7-default-rtdb.firebaseio.com',
    storageBucket: 'hotel-savior-b57f7.appspot.com',
    iosClientId: '638499786075-3e6od4chp45gq2ftm46aoea434eu66q5.apps.googleusercontent.com',
    iosBundleId: 'com.savior.hotel.hotelSavior',
  );
}
